//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.10 at 09:37:38 PM MSK 
//


package org.myeducation.taskexecuter.core.processor.scheme.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Elements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Elements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resistors" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Resistor" maxOccurs="unbounded"/>
 *         &lt;element name="capacitors" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Capacitor" maxOccurs="unbounded"/>
 *         &lt;element name="inductors" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Inductor" maxOccurs="unbounded"/>
 *         &lt;element name="transistors" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Transistor" maxOccurs="unbounded"/>
 *         &lt;element name="diodes" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Diode" maxOccurs="unbounded"/>
 *         &lt;element name="switches" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Switch" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Elements", propOrder = {
    "resistors",
    "capacitors",
    "inductors",
    "transistors",
    "diodes",
    "switches"
})
public class Elements {

    @XmlElement(required = true)
    protected List<Resistor> resistors;
    @XmlElement(required = true)
    protected List<Capacitor> capacitors;
    @XmlElement(required = true)
    protected List<Inductor> inductors;
    @XmlElement(required = true)
    protected List<Transistor> transistors;
    @XmlElement(required = true)
    protected List<Diode> diodes;
    @XmlElement(required = true)
    protected List<Switch> switches;

    /**
     * Gets the value of the resistors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resistors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResistors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Resistor }
     * 
     * 
     */
    public List<Resistor> getResistors() {
        if (resistors == null) {
            resistors = new ArrayList<Resistor>();
        }
        return this.resistors;
    }

    /**
     * Gets the value of the capacitors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capacitors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapacitors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capacitor }
     * 
     * 
     */
    public List<Capacitor> getCapacitors() {
        if (capacitors == null) {
            capacitors = new ArrayList<Capacitor>();
        }
        return this.capacitors;
    }

    /**
     * Gets the value of the inductors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inductors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInductors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inductor }
     * 
     * 
     */
    public List<Inductor> getInductors() {
        if (inductors == null) {
            inductors = new ArrayList<Inductor>();
        }
        return this.inductors;
    }

    /**
     * Gets the value of the transistors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transistors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransistors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transistor }
     * 
     * 
     */
    public List<Transistor> getTransistors() {
        if (transistors == null) {
            transistors = new ArrayList<Transistor>();
        }
        return this.transistors;
    }

    /**
     * Gets the value of the diodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Diode }
     * 
     * 
     */
    public List<Diode> getDiodes() {
        if (diodes == null) {
            diodes = new ArrayList<Diode>();
        }
        return this.diodes;
    }

    /**
     * Gets the value of the switches property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the switches property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwitches().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Switch }
     * 
     * 
     */
    public List<Switch> getSwitches() {
        if (switches == null) {
            switches = new ArrayList<Switch>();
        }
        return this.switches;
    }

}
