//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 11:22:14 PM MSK 
//


package org.myeducation.taskexecuter.core.processor.scheme.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Elements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Elements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resistor" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Resistor" maxOccurs="unbounded"/>
 *         &lt;element name="capacitor" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Capacitor" maxOccurs="unbounded"/>
 *         &lt;element name="inductor" type="{http://jaxb.scheme.processor.core.taskexecuter.myeducation.org/}Inductor" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Elements", propOrder = {
    "resistor",
    "capacitor",
    "inductor"
})
public class Elements {

    @XmlElement(required = true)
    protected List<Resistor> resistor;
    @XmlElement(required = true)
    protected List<Capacitor> capacitor;
    @XmlElement(required = true)
    protected List<Inductor> inductor;

    /**
     * Gets the value of the resistor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resistor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResistor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Resistor }
     * 
     * 
     */
    public List<Resistor> getResistor() {
        if (resistor == null) {
            resistor = new ArrayList<Resistor>();
        }
        return this.resistor;
    }

    /**
     * Gets the value of the capacitor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capacitor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapacitor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Capacitor }
     * 
     * 
     */
    public List<Capacitor> getCapacitor() {
        if (capacitor == null) {
            capacitor = new ArrayList<Capacitor>();
        }
        return this.capacitor;
    }

    /**
     * Gets the value of the inductor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inductor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInductor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Inductor }
     * 
     * 
     */
    public List<Inductor> getInductor() {
        if (inductor == null) {
            inductor = new ArrayList<Inductor>();
        }
        return this.inductor;
    }

}
