//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.11 at 12:57:28 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rules.jaxb.circuit.processor.core.taskexecuter.myeducation.org/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.myeducation.taskexecuter.core.processor.circuit.jaxb.rules;
